


1 Plot the 30-day mortality rates for heart attack
```{r}
outcome = read.csv("../../dataset/hospital/outcome-of-care-measures.csv", colClasses = "character")
head(outcome)
print(ncol(outcome))
print(names(outcome))
```
```{r}
outcome[, 11] <- as.numeric(outcome[, 11])
hist(outcome[, 11])

```

2 Finding the best hospital in a state
```{r}
best = function(state, outcome) {
  data = read.csv("../../dataset/hospital/outcome-of-care-measures.csv", colClasses = "character")
  disease_list = c("heart attack", "heart failure", "pneumonia")
  if (state %in% data$State & outcome %in% disease_list) {
    StateData = subset(data, State == state)
    if (outcome == "heart attack") { 
      StateData = StateData[c("Hospital.Name","Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack")]
    }
    else if (outcome == "heart failure"){
      StateData = StateData[c("Hospital.Name","Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure")]
    }
    else {
      StateData = StateData[c("Hospital.Name", "Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia")]
    }
    colnames(StateData) = c("Hospital.Name", "Disease.Rate")
    StateData[, "Disease.Rate"] = as.numeric(as.character(StateData[, "Disease.Rate"]))
    StateData[, "Hospital.Name"] = as.character(StateData[, "Hospital.Name"])
    StateData = StateData[order(StateData$Disease.Rate, StateData$Hospital.Name), ]
    StateData = na.omit(StateData)
    result = StateData$Hospital.Name[1]
    return (result)
  }
  return (NULL)
}

```

```{r}
best("TX", "heart attack")
best("TX", "heart failure")
best("MD", "heart attack")
best("MD", "pneumonia")
best("BB", "heart attack") #Error in best("BB", "heart attack") : invalid state

best("NY", "hert attack") # Error in best("NY", "hert attack") : invalid outcome
```

3 Ranking hospitals by outcome in a state
```{r}
rankhospital = function(state, outcome, num) {
  data = read.csv("../../dataset/hospital/outcome-of-care-measures.csv", colClasses = "character")
  disease_list = c("heart attack", "heart failure", "pneumonia")
  if (!(state %in% data$State)) {
    print("invalid state")
    return(NA)
  }
  if (!(outcome %in% disease_list)) {
    print("invalid disease")
    return(NA)
  }
  StateData = subset(data, State == state)
  if (outcome == "heart attack") { 
    StateData = StateData[c("Hospital.Name","Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack")]
  }
  else if (outcome == "heart failure"){
    StateData = StateData[c("Hospital.Name","Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure")]
  }
  else {
    StateData = StateData[c("Hospital.Name", "Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia")]
  }
  colnames(StateData) = c("Hospital.Name", "Disease.Rate")
  StateData[, "Disease.Rate"] = as.numeric(as.character(StateData[, "Disease.Rate"]))
  StateData[, "Hospital.Name"] = as.character(StateData[, "Hospital.Name"])
  StateData = StateData[order(StateData$Disease.Rate, StateData$Hospital.Name), ]
  StateData = na.omit(StateData)
  if (num == "best") {
    result = StateData$Hospital.Name[1]
  }
  if (num == "worst") {
    N = sum(!is.na(StateData$Disease.Rate))
    result = StateData$Hospital.Name[N]
  }
  else if (num > length(StateData$Hospital) | num <= 0) {
    print("invalid num")
    return(NA)
  }
  else {
    result = StateData$Hospital.Name[num]
  }
  return (result)
}
```

```{r}
rankhospital("TX", "heart failure", 4)
rankhospital("MD", "heart attack", "worst")
rankhospital("MN", "heart attack", 5000) # should return NA
```

4 Ranking hospitals in all states
```{r}
rankall = function(outcome, num = "best") {
  data = read.csv("../../dataset/hospital/outcome-of-care-measures.csv", colClasses = "character")
  disease_list = c("heart attack", "heart failure", "pneumonia")
  Statelist = as.character(unique(data$State))
  
  if (!(outcome %in% disease_list)) {
    print("invalid disease")
    return(NA)
  }
  
  if (outcome == "heart attack") { 
    data = data[c("Hospital.Name", "State", "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Attack")]
  }
  else if (outcome == "heart failure"){
    data = data[c("Hospital.Name", "State", "Hospital.30.Day.Death..Mortality..Rates.from.Heart.Failure")]
  }
  else {
    data = data[c("Hospital.Name", "State", "Hospital.30.Day.Death..Mortality..Rates.from.Pneumonia")]
  }
  
  colnames(data)[3] = "Disease.Rate"
  data[, "Disease.Rate"] = as.numeric(as.character(data[, "Disease.Rate"]))
  data[, "Hospital.Name"] = as.character(data[, "Hospital.Name"])
  
  result_data = data.frame()
  for (i in seq_len(length(Statelist))){
    StateData = subset(data, State == Statelist[i])
    StateData = StateData[order(StateData$Disease.Rate, StateData$Hospital.Name), ]
    StateData = na.omit(StateData)
    hospital_name = NA
    if (num == "best"){
      num = 1
    }
    if (num == "worst"){
      N = sum(!is.na(StateData$Disease.Rate))
      num = N
    }
    if (num > length(StateData$Hospital) | num <= 0) {
      next
    }
    hospital_name = StateData$Hospital.Name[num]
    tmp = data.frame(hospital_name, Statelist[i])
    colnames(tmp) = c("hospital", "state") 
    result_data = rbind(result_data, tmp)
  }
  return (result_data)
}
```

```{r}
head(rankall("heart attack", 20), 10)
tail(rankall("pneumonia", "worst"), 3)
tail(rankall("heart failure"), 10)
```

